Protected delete
DominatingDevs/capstone-loosey-goosey pull request #7
Opened 2022-06-03 20:55 UTC by Kmmontes

2022-06-03 21:08 UTC, elysemontano requested changes
Left some comments.  Please remove any extra console logs and make sure all IDs in state are dynamic and not hard-coded.

2022-06-03 21:08 UTC, elysemontano commented on app/javascript/components/App.js
> +          {/* <Route path="/gooseyshow/:id"
Are you using this?  If not can it be removed?

2022-06-03 21:08 UTC, elysemontano commented on app/javascript/components/components/DeleteGooseyButton.js
> +        <NavLink to= "/mygooseylist">
Indentation

2022-06-03 21:08 UTC, elysemontano commented on app/javascript/components/components/EditGooseyButton.js
> +import React, { Component } from 'react'
Double check your indentation on this component.

2022-06-03 21:08 UTC, elysemontano commented on app/javascript/components/pages/GooseyEdit.js
> +            id: 23,
This should not be hard coded.  Try using this.props.listing.id

2022-06-03 21:08 UTC, elysemontano commented on app/javascript/components/pages/GooseyEdit.js
> +      console.log(this.props)
Please remove these console logs.

2022-06-03 21:08 UTC, elysemontano commented on app/javascript/components/pages/GooseyEdit.js
> +
Can we delete this?

2022-06-03 21:08 UTC, elysemontano commented on app/javascript/components/pages/GooseyShow.js
> +                  </div>}
Please double-check your indentation.

2022-06-03 21:08 UTC, elysemontano commented on app/javascript/components/pages/MyGooseyList.js
> +      id: 1,
This should be dynamic and not hardcoded.

2022-06-03 21:08 UTC, elysemontano commented on app/javascript/components/pages/MyGooseyList.js
> +            </div>
Check indentation

2022-06-06 16:44 UTC, triciasykes approved these changes

2022-06-06 16:48 UTC, triciasykes approved these changes

2022-06-06 16:54 UTC, merged